### ISSUE TITLE
Unable to build m2

### ISSUE THREAD

**Issue by seancmartin** [IIIF/m2#373]
I used the build instructions at https://github.com/IIIF/mirador to try and build m2. I failed. index.html references a script at build/mirador/mirador.js; however, this was not present after trying to build. Its possible that the file is created but is in a different directory. The same situation may apply to other files/directories

**Comment by aeschylus** [comment]
Hi Sean. Those build instructions are for the mirador project, not m2 (I realise this is somewhat confusing). Please follow the instructions on the [m2 wiki](https://github.com/IIIF/m2/wiki/Developer-Tooling-and-Workflow#workflow). The same steps are used to automatically build the project for testing, and I also just tested a fresh manual install for you. All seems good. Let me know if you run into any hitches or annoyances.

We are releasing at the end of next week, and want to experimentation process to be smooth for newcomers, so please feel free to add any feedback on the install experience here.

**Comment by aeschylus** [comment]
Marking this as closed for now. Let me know if you have any more trouble.

**Comment by seancmartin** [comment]
Many thanks. Apologies I have been travelling and am now back home. I'm 
sure it will be fine.

All best

Sean
