### ISSUE TITLE
deleted slots stay deleted when changing layout

### ISSUE THREAD

**Issue by azaroth42** [IIIF/m2#393]
Steps to reproduce:

1.  Go into 3x3 mode
2.  Load an object into middle right slot
3.  Close (making columns of 3,3,2)
4.  Change layout to 2x2
5.  Change layout back to 3x3

Expected result: 3x3 layout
Actual result: 3,3,2 layout as per step 3

**Comment by aeschylus** [comment]
This probably has to do with the workspace redefining the layout and saving it in calculateLayout. This mechanism is no longer the same in the refactor branch, so the revision should eliminate this bug.

**Comment by rsinghal** [comment]
Correct, Isfahan is adding information and changing the layout description.  The new way of providing users with pre-defined layouts will resolve this.
