### ISSUE TITLE
Choose New Layout screen hangs

### ISSUE THREAD

**Issue by azaroth42** [IIIF/m2#399]
Click the new layout button and the resulting screen displays only the heading, no options.
(on sul-reader-test as of 11am 29/1/15)
![screen shot 2015-01-29 at 10 54 19 am](https://cloud.githubusercontent.com/assets/871868/5963965/65a5c510-a7a5-11e4-9520-4e3be7a428f4.png)

**Comment by rsinghal** [comment]
Correct, there is nothing to populate that screen right now, but will be re-added in the next day or two.

**Comment by aeschylus** [comment]
Yep, this feature is currently disabled as it is being refactored. I will remove the button as well.
