### ISSUE TITLE
Edit mode for an annotation - disable all other tooltips?

### ISSUE THREAD

**Issue by rsinghal** [IIIF/m2#432]
When a user attempts to edit an annotation should:

- the editor stay on the window even if the user mouses away from the overlay?
- disable the mouseenter events for other overlays so other annos/tooltips can't be displayed?

Event listeners would need to be more nuanced if multiple qtips were open at the same time.

**Comment by aeschylus** [comment]
I think it makes the most sense to freeze them entirely until they save or
cancel.

They are in a mode, similar to how the panning and zooming are disabled
while drawing a box.

Long live modes.

**Comment by rsinghal** [comment]
Agreed, both of those are now set.
