### ISSUE TITLE
workspacepanel in mirador.js problem

### ISSUE THREAD

**Issue by higginsr** [IIIF/m2#464]
Build c657f7db4a
Throws a javascript type error on loading index.html and other example viewers, on line 3143 of mirador.js, that WorkspacePanel is not a constructor and loads a blank viewer.
If you comment the line out, the viewer will load but the add item option only pops up for a few seconds before Gough Liturg. 19 is displayed and there is no option to load other manifests.

**Comment by rsinghal** [comment]
@aeschylus File is missing from commit
