### ISSUE TITLE
"dead click" spots in ManifestListItems.

### ISSUE THREAD

**Issue by pobocks** [IIIF/m2#481]
Spaces between thumbnails, end of ManifestListItem, etc, are not clickable, but show clickable cursor and are logically part of the item that could be used for selection. 

I think making the entire item clickable, and stopping propagation in any handlers for subElements that need special handling (right now just thumbnails) seems like reasonable behavior.

**Comment by aeschylus** [comment]
Agreed.

**Comment by aeschylus** [comment]
Nice. This is what I would have done for the problem. I'll merge this as soon as I test it out.
